# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2021-09-24 17:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_login', '0001_initial'),
        ('snippet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='fk_created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='user_login.UserDetails'),
        ),
        migrations.AddField(
            model_name='snippet',
            name='fk_tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='snippet.Tag'),
        ),
    ]
